"""add interrupted_at to agent_runs

Revision ID: 370ee3c8987d
Revises: 20260904_0001
Create Date: 2026-09-14 21:12:24.378836
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '370ee3c8987d'
down_revision: Union[str, None] = '20260904_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('interrupted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'interrupted_at')
    # ### end Alembic commands ###

