"""add degraded_summary to agent_runs

Revision ID: c78153d58823
Revises: 370ee3c8987d
Create Date: 2026-09-14 22:04:02.769303
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = 'c78153d58823'
down_revision: Union[str, None] = '370ee3c8987d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('degraded_summary', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'degraded_summary')
    # ### end Alembic commands ###

